# This action runs every day at 6 AM and on every push
# If the branch it's running on is main then it will run snyk monitor (reports vulnerabilities to snyk.io)
# Otherwise it will run snyk test
# NOTE: This repository uses master as the default branch (this file will need updating when it moves to main)
# UPDATED NOTE: This repository has been updated to main as its default branch - see master-to-main output below for more info
# ✔ Checking that the repository exists
# ✔ Checking that the master branch exists
# ✔ Checking that the main branch does not exist
# ✔ Checking that you have the required permissions
#   > Getting username from access token
#   > Getting repositoring permissions for user
# ✔ Checking the number of open pull requests to master and confirming actions with user
# ✔ This script would now update the master branch to main on the guardian/compare-dates repository. 1 open pull requests would be updated.
# Are you happy to proceed? … yes
# ✔ Renaming the branch master to main
# ✔ Checking to see if a riff-raff.yaml file exists
# > No riff-raff.yaml file found
# ✔ Checking to see if any files reference master
# > No references found
# ✔ Opening issue regarding other configuration
name: Snyk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  security:
    uses: guardian/.github/.github/workflows/sbt-node-snyk.yml@main
    with:
      DEBUG: true
      ORG: guardian
      SKIP_NODE: true
    secrets:
       SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
